[versions]
agp = "8.9.1"
kotlin = "2.0.21"
xposedbridge = "main-SNAPSHOT"

[libraries]
xposedbridge = { module = "com.github.Mahmud0808:XposedBridge", version.ref = "xposedbridge" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

